
package vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JDesktopPane;

/**
 *
 * @author USER
 */
public class FrmMenu extends javax.swing.JFrame {
    
    public static JDesktopPane jDesktopPane_menu;

    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de ventas de videojuegos");
        
        this.setLayout(null);
        jDesktopPane_menu = new EstiloFondo();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0,0, ancho, (alto-110));
        this.add(jDesktopPane_menu);
            }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/aplicacion.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3_nuevo_videojuego = new javax.swing.JMenuItem();
        jMenuItem4_gestionar_videojuegos = new javax.swing.JMenuItem();
        jMenuItem5_actualizar_stock = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem9_gestionar_categorias = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem10_nueva_plataforma = new javax.swing.JMenuItem();
        jMenuItem11_gestionar_plataformas = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem20_cerrar_sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(133, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/videojuego.png"))); // NOI18N
        jMenu2.setText("Videojuegos");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(160, 50));

        jMenuItem3_nuevo_videojuego.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem3_nuevo_videojuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevoJuego.png"))); // NOI18N
        jMenuItem3_nuevo_videojuego.setText("Nuevo Videojuego");
        jMenuItem3_nuevo_videojuego.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem3_nuevo_videojuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_nuevo_videojuegoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3_nuevo_videojuego);

        jMenuItem4_gestionar_videojuegos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem4_gestionar_videojuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestionar juegos.png"))); // NOI18N
        jMenuItem4_gestionar_videojuegos.setText("Gestionar Videojuego");
        jMenuItem4_gestionar_videojuegos.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem4_gestionar_videojuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_gestionar_videojuegosActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_gestionar_videojuegos);

        jMenuItem5_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem5_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/stock.png"))); // NOI18N
        jMenuItem5_actualizar_stock.setText("Actualizar Stock");
        jMenuItem5_actualizar_stock.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenu2.add(jMenuItem5_actualizar_stock);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(155, 50));

        jMenuItem8_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem8_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva-categoria.png"))); // NOI18N
        jMenuItem8_nueva_categoria.setText("Nueva Categoria");
        jMenuItem8_nueva_categoria.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem8_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8_nueva_categoria);

        jMenuItem9_gestionar_categorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem9_gestionar_categorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categoria.png"))); // NOI18N
        jMenuItem9_gestionar_categorias.setText("Gestionar Categorias");
        jMenuItem9_gestionar_categorias.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem9_gestionar_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_gestionar_categoriasActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9_gestionar_categorias);

        jMenuBar1.add(jMenu4);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plataforma.png"))); // NOI18N
        jMenu9.setText("Plataforma");
        jMenu9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu9.setPreferredSize(new java.awt.Dimension(155, 50));

        jMenuItem10_nueva_plataforma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem10_nueva_plataforma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nueva-plataforma.png"))); // NOI18N
        jMenuItem10_nueva_plataforma.setText("Nueva Plataforma");
        jMenuItem10_nueva_plataforma.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem10_nueva_plataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10_nueva_plataformaActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem10_nueva_plataforma);

        jMenuItem11_gestionar_plataformas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem11_gestionar_plataformas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gestion-plataforma.png"))); // NOI18N
        jMenuItem11_gestionar_plataformas.setText("Gestionar Plataformas");
        jMenuItem11_gestionar_plataformas.setPreferredSize(new java.awt.Dimension(300, 40));
        jMenuItem11_gestionar_plataformas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11_gestionar_plataformasActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem11_gestionar_plataformas);

        jMenuBar1.add(jMenu9);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar Sesión");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setMinimumSize(new java.awt.Dimension(156, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(162, 50));

        jMenuItem20_cerrar_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem20_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem20_cerrar_sesion.setText("Cerrar Sesión");
        jMenuItem20_cerrar_sesion.setPreferredSize(new java.awt.Dimension(250, 30));
        jMenuItem20_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20_cerrar_sesionActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem20_cerrar_sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem8_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_nueva_categoriaActionPerformed
        InterCategoria interCategoria = new InterCategoria();
        jDesktopPane_menu.add(interCategoria);
        interCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem8_nueva_categoriaActionPerformed

    private void jMenuItem10_nueva_plataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10_nueva_plataformaActionPerformed
        InterPlataforma interPlataforma =new InterPlataforma();
        jDesktopPane_menu.add(interPlataforma);
        interPlataforma.setVisible(true);
    }//GEN-LAST:event_jMenuItem10_nueva_plataformaActionPerformed

    private void jMenuItem9_gestionar_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_gestionar_categoriasActionPerformed
        InterGestionarCategorias categorias = new InterGestionarCategorias();
        jDesktopPane_menu.add(categorias);
        categorias.setVisible(true);
    }//GEN-LAST:event_jMenuItem9_gestionar_categoriasActionPerformed

    private void jMenuItem11_gestionar_plataformasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11_gestionar_plataformasActionPerformed
        InterGestionarPlataforma gestionarPlataforma = new InterGestionarPlataforma();
        jDesktopPane_menu.add(gestionarPlataforma);
        gestionarPlataforma.setVisible(true);
    }//GEN-LAST:event_jMenuItem11_gestionar_plataformasActionPerformed

    private void jMenuItem3_nuevo_videojuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_nuevo_videojuegoActionPerformed
        InterVideojuego interVideojuego = new InterVideojuego();
        jDesktopPane_menu.add(interVideojuego);
        interVideojuego.setVisible(true);
    }//GEN-LAST:event_jMenuItem3_nuevo_videojuegoActionPerformed

    private void jMenuItem4_gestionar_videojuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_gestionar_videojuegosActionPerformed
        InterGestionarVideojuego gestionarVideojuego = new InterGestionarVideojuego();
        jDesktopPane_menu.add(gestionarVideojuego);
        gestionarVideojuego.setVisible(true);
    }//GEN-LAST:event_jMenuItem4_gestionar_videojuegosActionPerformed

    private void jMenuItem20_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20_cerrar_sesionActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem20_cerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10_nueva_plataforma;
    private javax.swing.JMenuItem jMenuItem11_gestionar_plataformas;
    private javax.swing.JMenuItem jMenuItem20_cerrar_sesion;
    private javax.swing.JMenuItem jMenuItem3_nuevo_videojuego;
    private javax.swing.JMenuItem jMenuItem4_gestionar_videojuegos;
    private javax.swing.JMenuItem jMenuItem5_actualizar_stock;
    private javax.swing.JMenuItem jMenuItem8_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem9_gestionar_categorias;
    // End of variables declaration//GEN-END:variables
}
