package vista;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import conexion.Conexion;
import controlador.Ctrl_Categoria;
import controlador.Ctrl_Plataforma;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.Plataforma;
import static vista.InterGestionarCategorias.jTable1_categorias;

/**
 *
 * @author USER
 */
public class InterGestionarPlataforma extends javax.swing.JInternalFrame {

    private int idPlataforma;
    private final String TABLA = "tb_plataforma";
    
    public InterGestionarPlataforma() {
        initComponents();
        this.setSize(new Dimension(750, 425));
        this.setTitle("Gestionar Plataformas");
        
        this.CargarTablaPlataformas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_plataformas = new javax.swing.JTable();
        jButton_refrescar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_estado = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txt_filtro = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aministrar Plataformas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_plataformas.setBackground(new java.awt.Color(255, 255, 255));
        jTable_plataformas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_plataformas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 444, 242));

        jButton_refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar Tabla.png"))); // NOI18N
        jButton_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refrescarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_refrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 510, 250));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_actualizar.setBackground(new java.awt.Color(26, 188, 156));
        jButton_actualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_actualizar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 7, 100, -1));

        jButton_eliminar.setBackground(new java.awt.Color(231, 76, 60));
        jButton_eliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 40, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 130, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Descripcion:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txt_descripcion.setBackground(new java.awt.Color(255, 255, 255));
        txt_descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_descripcion.setForeground(new java.awt.Color(0, 0, 0));
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        jPanel3.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        txt_estado.setBackground(new java.awt.Color(255, 255, 255));
        txt_estado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txt_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 170, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 190, 150));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filtroActionPerformed(evt);
            }
        });
        txt_filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_filtroKeyPressed(evt);
            }
        });
        jPanel4.add(txt_filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, -1));

        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar (1).png"))); // NOI18N
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 670, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        if(!txt_estado.getText().isEmpty()){
            Plataforma plataforma = new Plataforma();
            Ctrl_Plataforma controlPlataforma = new Ctrl_Plataforma();
            
            plataforma.setDescripcion(txt_descripcion.getText().trim());
            plataforma.setEstado(Integer.parseInt(txt_estado.getText().trim()));
            if(txt_descripcion.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Ingrese una descripcion para guardar");
                txt_descripcion.setBackground(Color.red);
            }else{
                if(controlPlataforma.Actualizar(plataforma, idPlataforma)){
                    JOptionPane.showMessageDialog(null,"Plataforma Actualizada");
                    txt_descripcion.setText("");
                    txt_descripcion.setBackground(Color.white);
                    txt_estado.setText("");
                    this.CargarTablaPlataformas();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al actualizar la Plataforma");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una Plataforma");
        }
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        if(!txt_estado.getText().isEmpty()){
            Plataforma plataforma = new Plataforma();
            Ctrl_Plataforma controlPlataforma = new Ctrl_Plataforma();
            
            plataforma.setDescripcion(txt_estado.getText().trim());
            if(controlPlataforma.Eliminar(idPlataforma)){
                JOptionPane.showMessageDialog(null,"Plataforma Eliminada");
                txt_estado.setText("");
                this.CargarTablaPlataformas();
            }else{
                JOptionPane.showMessageDialog(null, "Error al Eliminar Plataforma");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una Plataforma");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        this.CargarTablaPlataformas(txt_filtro.getText().trim());
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refrescarActionPerformed
        // TODO add your handling code here:
        this.CargarTablaPlataformas();
        txt_filtro.setText("");
    }//GEN-LAST:event_jButton_refrescarActionPerformed

    private void txt_filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filtroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_filtroActionPerformed

    private void txt_filtroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filtroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            this.CargarTablaPlataformas(txt_filtro.getText().trim());
        }
    }//GEN-LAST:event_txt_filtroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_refrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable_plataformas;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_estado;
    private javax.swing.JTextField txt_filtro;
    // End of variables declaration//GEN-END:variables

    private void CargarTablaPlataformas(){
        Connection con = (Connection) Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql="select idPlataforma, descripcion, estado from "+TABLA;
        Statement st;
        
        try {
            st =(Statement) con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            InterGestionarPlataforma.jTable_plataformas = new JTable(model);
            InterGestionarPlataforma.jScrollPane1.setViewportView(InterGestionarPlataforma.jTable_plataformas);
            
            model.addColumn("idPlataforma");
            model.addColumn("descripcion");
            model.addColumn("estado");
            
            while(rs.next()){
                Object fila[] = new Object[3];
                
                for(int i = 0; i<3; i++){
                    fila[i] = rs.getObject(i+1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llamar la tabla plataformas: "+e);
        }
        
        jTable_plataformas.addMouseListener(new MouseAdapter(){
           @Override
           public void mouseClicked(MouseEvent e){
               int fila_point =jTable_plataformas.rowAtPoint(e.getPoint());
               int columna_point = 0;
               if(fila_point > -1){
                   idPlataforma = (int) model.getValueAt(fila_point, columna_point);
                   EnviarDatosCategoriaSeleccionada(idPlataforma);
               }
           }  
        });
    }
    
    private void EnviarDatosCategoriaSeleccionada(int idPlataforma){
        try {
            Connection con = (Connection) Conexion.conectar();
            PreparedStatement pat = (PreparedStatement) con.prepareStatement(
                    "select * from "+TABLA+" WHERE idPlataforma = '"+idPlataforma+"';");
            ResultSet rs = pat.executeQuery();
            
            if(rs.next()){
                txt_descripcion.setText(rs.getString("descripcion"));
                txt_estado.setText(rs.getString("estado"));
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error al seleccionar Plataforma: "+ e);
        }        
    }
    
    private void CargarTablaPlataformas(String descripcion){
        Connection con = (Connection) Conexion.conectar();
        DefaultTableModel model = new DefaultTableModel();
        String sql="select idPlataforma, descripcion, estado from "+TABLA+" where descripcion LIKE'"+descripcion+"%';";
        Statement st;
        
        try {
            st =(Statement) con.createStatement();
            ResultSet rs= st.executeQuery(sql);
            InterGestionarPlataforma.jTable_plataformas = new JTable(model);
            InterGestionarPlataforma.jScrollPane1.setViewportView(InterGestionarPlataforma.jTable_plataformas);
            
            model.addColumn("idPlataforma");
            model.addColumn("descripcion");
            model.addColumn("estado");
            
            while(rs.next()){
                Object fila[] = new Object[3];
                
                for(int i = 0; i<3; i++){
                    fila[i] = rs.getObject(i+1);
                }
                model.addRow(fila);
            }
            con.close();
        } catch (SQLException e) {
            System.out.println("Error al llamar la tabla plataformas: "+e);
        }
        
        jTable_plataformas.addMouseListener(new MouseAdapter(){
           @Override
           public void mouseClicked(MouseEvent e){
               int fila_point =jTable_plataformas.rowAtPoint(e.getPoint());
               int columna_point = 0;
               if(fila_point > -1){
                   idPlataforma = (int) model.getValueAt(fila_point, columna_point);
                   EnviarDatosCategoriaSeleccionada(idPlataforma);
               }
           }  
        });
    }
}
